In [ ]:
### Load relevant packages
import pandas                  as pd
import numpy                   as np
import matplotlib.pyplot       as plt
import seaborn                 as sns
import statsmodels.formula.api as sm
import os

%matplotlib inline
plt.style.use('ggplot')

In [ ]:
## Using file from the drive
from google.colab import drive
drive.mount('/content/drive')
!ls
df = pd.read_csv('/content/drive/Shared drives/Data Science for All - Womens Summit/Data/US Crunchbase Companies.csv')
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
drive  sample_data

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (6,7,9,18,26,28,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,48,51,53,54,56,58,60,62,64,66,67,69,74,76,78,82,83,85,87,88,90,94,95,96,97,98,99,100,101,102,103,104,105,107,108,109,110,111,112,113,114,115,118,120) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

   Index  ... Aberdeen - IT Spend Currency (in USD)
0      1  ...                                   NaN
1      2  ...                                   NaN
2      3  ...                                   NaN
3      4  ...                                   NaN
4      5  ...                                 32109

[5 rows x 121 columns]

In [ ]:
## Column headers
df.columns.values

array(['Index', 'Organization Name', 'Organization Name URL',
       'Industries', 'Headquarters Location', 'Description',
       'CB Rank (Company)', 'Total Funding Amount',
       'Total Funding Amount Currency',
       'Total Funding Amount Currency (in USD)', 'Founded Date',
       'Founded Date Precision', 'Headquarters Regions',
       'Diversity Spotlight (US Only)', 'Estimated Revenue Range',
       'Operating Status', 'Full Description', 'Hub Tags',
       'Number of Articles', 'Phone Number', 'Contact Email', 'LinkedIn',
       'Facebook', 'Twitter', 'Website', 'Company Type', 'Closed Date',
       'Closed Date Precision', 'Exit Date', 'Exit Date Precision',
       'Investor Type', 'Investment Stage',
       'Number of Portfolio Organizations', 'Number of Investments',
       'Number of Lead Investments', 'Number of Diversity Investments',
       'Number of Exits', 'Number of Exits (IPO)',
       'Accelerator Program Type', 'Accelerator Application Deadline',
       'Accelerator Duration (in weeks)', 'School Type', 'School Program',
       'Number of Enrollments', 'School Method',
       'Number of Founders (Alumni)', 'Number of Alumni',
       'Industry Groups', 'Number of Founders', 'Founders',
       'Number of Employees', 'Number of Funding Rounds',
       'Funding Status', 'Last Funding Date', 'Last Funding Amount',
       'Last Funding Amount Currency',
       'Last Funding Amount Currency (in USD)', 'Last Funding Type',
       'Last Equity Funding Amount',
       'Last Equity Funding Amount Currency',
       'Last Equity Funding Amount Currency (in USD)',
       'Last Equity Funding Type', 'Total Equity Funding Amount',
       'Total Equity Funding Amount Currency',
       'Total Equity Funding Amount Currency (in USD)', 'Top 5 Investors',
       'Number of Lead Investors', 'Number of Investors',
       'Acquisition Status', 'Number of Acquisitions', 'Transaction Name',
       'Transaction Name URL', 'Acquired by', 'Acquired by URL',
       'Announced Date', 'Announced Date Precision', 'Price',
       'Price Currency', 'Price Currency (in USD)', 'Acquisition Type',
       'Acquisition Terms', 'IPO Status', 'IPO Date', 'Delisted Date',
       'Delisted Date Precision', 'Money Raised at IPO',
       'Money Raised at IPO Currency',
       'Money Raised at IPO Currency (in USD)', 'Valuation at IPO',
       'Valuation at IPO Currency', 'Valuation at IPO Currency (in USD)',
       'Stock Symbol', 'Stock Symbol URL', 'Stock Exchange',
       'Last Leadership Hiring Date', 'Number of Events',
       'CB Rank (Organization)', 'CB Rank (School)',
       'Trend Score (7 Days)', 'Trend Score (30 Days)',
       'Trend Score (90 Days)', 'SEMrush - Monthly Visits',
       'SEMrush - Average Visits (6 months)',
       'SEMrush - Monthly Visits Growth', 'SEMrush - Visit Duration',
       'SEMrush - Visit Duration Growth', 'SEMrush - Page Views / Visit',
       'SEMrush - Page Views / Visit Growth', 'SEMrush - Bounce Rate',
       'SEMrush - Bounce Rate Growth', 'BuiltWith - Active Tech Count',
       'Apptopia - Number of Apps', 'Apptopia - Downloads Last 30 Days',
       'G2 Stack - Total Products Active', 'IPqwery - Patents Granted',
       'IPqwery - Trademarks Registered',
       'IPqwery - Most Popular Trademark Class',
       'IPqwery - Most Popular Patent Class', 'Aberdeen - IT Spend',
       'Aberdeen - IT Spend Currency',
       'Aberdeen - IT Spend Currency (in USD)'], dtype=object)

In [ ]:
## All categories in the Diversity Spotlight column
df['Diversity Spotlight (US Only)'].unique()

array([nan, 'Women Founded', 'Women Led', 'Women Founded, Women Led',
       'Hispanic / Latinx Founded',
       'Black / African American Founded, Black / African American Led',
       'Black / African American Founded, Black / African American Led, Women Founded, Women Led',
       'Black / African American Led',
       'Hispanic / Latinx Founded, Hispanic / Latinx Led',
       'Black / African American Founded',
       'East Asian Founded, East Asian Led',
       'Hispanic / Latinx Founded, Hispanic / Latinx Led, South Asian Founded, South Asian Led',
       'Hispanic / Latinx Founded, Hispanic / Latinx Led, Women Founded, Women Led',
       'Black / African American Founded, Middle Eastern / North African Founded',
       'East Asian Founded',
       'East Asian Founded, East Asian Led, Women Founded',
       'Hispanic / Latinx Founded, Women Founded', 'South Asian Founded',
       'Middle Eastern / North African Founded, Middle Eastern / North African Led, Women Founded, Women Led',
       'South Asian Founded, South Asian Led',
       'Hispanic / Latinx Founded, Middle Eastern / North African Founded, Native Hawaiian / Pacific Islander Founded, Southeast Asian Founded, Women Founded, Women Led',
       'East Asian Founded, Southeast Asian Founded, Women Founded',
       'Hispanic / Latinx Founded, Hispanic / Latinx Led, Women Founded',
       'East Asian Led, Middle Eastern / North African Led, Women Founded',
       'South Asian Founded, South Asian Led, Women Founded',
       'Black / African American Founded, Women Founded',
       'Middle Eastern / North African Founded',
       'Native Hawaiian / Pacific Islander Founded, Native Hawaiian / Pacific Islander Led',
       'East Asian Led, Women Founded, Women Led',
       'Hispanic / Latinx Founded, Women Founded, Women Led',
       'East Asian Led',
       'Black / African American Founded, Women Founded, Women Led',
       'Middle Eastern / North African Founded, Middle Eastern / North African Led',
       'South Asian Founded, Women Founded',
       'Black / African American Founded, Black / African American Led, Women Founded',
       'American Indian / Alaska Native Led, Hispanic / Latinx Founded, Women Founded, Women Led',
       'American Indian / Alaska Native Led, Women Founded',
       'American Indian / Alaska Native Founded',
       'Black / African American Led, East Asian Led, Women Founded',
       'Black / African American Founded, Black / African American Led, South Asian Founded',
       'Southeast Asian Led', 'Hispanic / Latinx Led',
       'Southeast Asian Founded, Southeast Asian Led, Women Founded, Women Led',
       'Southeast Asian Founded, Southeast Asian Led',
       'East Asian Founded, East Asian Led, Women Founded, Women Led',
       'South Asian Founded, South Asian Led, Southeast Asian Founded',
       'Black / African American Founded, Black / African American Led, Hispanic / Latinx Founded',
       'Black / African American Founded, Hispanic / Latinx Founded, Women Founded, Women Led',
       'Black / African American Founded, Hispanic / Latinx Founded, Women Founded',
       'South Asian Founded, Women Founded, Women Led',
       'Southeast Asian Founded',
       'East Asian Founded, South Asian Founded, South Asian Led',
       'East Asian Founded, East Asian Led, Middle Eastern / North African Founded',
       'South Asian Founded, South Asian Led, Women Founded, Women Led',
       'Black / African American Founded, Black / African American Led, South Asian Founded, South Asian Led',
       'Black / African American Founded, Black / African American Led, Hispanic / Latinx Founded, Hispanic / Latinx Led, Women Founded, Women Led',
       'Black / African American Founded, Hispanic / Latinx Founded, Hispanic / Latinx Led',
       'East Asian Founded, Women Founded',
       'South Asian Led, Women Founded',
       'Hispanic / Latinx Led, Women Founded',
       'Black / African American Founded, Black / African American Led, Hispanic / Latinx Founded, Hispanic / Latinx Led, Women Founded',
       'Hispanic / Latinx Founded, Native Hawaiian / Pacific Islander Founded, South Asian Founded',
       'Black / African American Founded, Women Led',
       'East Asian Founded, Women Founded, Women Led', 'South Asian Led',
       'Black / African American Founded, Southeast Asian Founded, Southeast Asian Led, Women Founded, Women Led',
       'Diversity Spotlight (US Only)'], dtype=object)

In [ ]:
# Women Founded or Led businesses
df_women = df[df['Diversity Spotlight (US Only)'].astype(str).str.contains("Women")]
df_women

         Index  ... Aberdeen - IT Spend Currency (in USD)
63          64  ...                                   NaN
84          85  ...                                108021
87          88  ...                                   NaN
105        106  ...                                   NaN
106        107  ...                                   NaN
...        ...  ...                                   ...
108897  108898  ...                                   NaN
108925  108926  ...                                   NaN
108952  108953  ...                                   NaN
108963  108964  ...                                   NaN
108965  108966  ...                                   NaN

[6019 rows x 121 columns]

In [ ]:
len(df_women)

6019

In [ ]:
# Percentage of women founded/led businesses
len(df_women)/len(df)

0.05519790176442537

5.5% of businesses are women-founded

In [ ]:
df_women['Total Funding Amount Currency (in USD)'] = df_women['Total Funding Amount Currency (in USD)'].fillna(0)
df_women

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

         Index  ... Aberdeen - IT Spend Currency (in USD)
63          64  ...                                   NaN
84          85  ...                                108021
87          88  ...                                   NaN
105        106  ...                                   NaN
106        107  ...                                   NaN
...        ...  ...                                   ...
108897  108898  ...                                   NaN
108925  108926  ...                                   NaN
108952  108953  ...                                   NaN
108963  108964  ...                                   NaN
108965  108966  ...                                   NaN

[6019 rows x 121 columns]

In [ ]:
df_less_than = df_women['Total Funding Amount Currency (in USD)'].astype('float') < 200000.0
df_less_than_200k = df_less_than[df_less_than==True]

In [ ]:
len(df_less_than_200k)

4059

In [ ]:
len(df_women)

6019

In [ ]:
len(df_less_than_200k)/len(df_women)

0.6743645123774713